### PR TITLE
Added sliding footer

### PR DESCRIPTION
**Pull request by mt-empty**
## Proposed changes

Added sliding footer to all pages

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by idomo1 — CHANGES_REQUESTED** [review]
Why make it sticky? Doesn't appear to be working as you intend anyway in Chrome at least. No need to overcomplicate this, it just needs to be a footer at the bottom of the page. I think the background should be black as well.
Why include contact us? That's something Zac is working on. Are you coordinating this with him?

**Comment by mt-empty** [comment]
> Doesn't appear to be working as you intend anyway in Chrome at least.
Can you elaborate, it works great on Chrome and Firefox.

> Why include contact us?
just a place holder, might get removed depending how @ZacWhittaker implements it.

**Comment by idomo1** [comment]
@mt-empty Here's what it looks like for me
https://user-images.githubusercontent.com/53201250/133872520-2c881afe-4b04-4bff-87b2-c67b8de5bcd5.mov

**Review by Akshith-Patil — CHANGES_REQUESTED** [review]
I don't think the footer should be sticky, it doesn't look very nice when scrolling. Also, the footer overlaps the image & video results on reportage, attached are some screenshots below. Also, I cannot click on the privacy policy link in the footer. 
Footer in reportPage

Footer in reportPage 2
.

**Comment by mt-empty** [comment]
Thanks @Akshith-Patil , this is what I was saying about the CSS not being organized, I had to apply the same rules to every CSS file.

**Comment by idomo1** [comment]
I think adding some elevation (drop shadow) to the element before the footer would make it look better, like it's sliding out from underneath it

**Comment by mt-empty** [comment]
@idomo1 I have spent two hours on this, I don't think I can implement it without major refactoring. The two methods that I have tried are:
`OnScroll` event: this is inefficient and I couldn't get it to work.
`IntersectionObserver` API: I can implement it in a hacky way, involves using magic numbers.

Or I could pass react reference among many files, and I don't think its a good idea.

**Review by idomo1 — APPROVED** [review]

**Review by Akshith-Patil — APPROVED** [review]
👍

**Pull request merged**
