### PR TITLE
Add custom heatmap theme picker

### PR DESCRIPTION
**Pull request by idomo1**
## Proposed changes

Allow users to pick a custom heatmap colour scheme

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

https://user-images.githubusercontent.com/53201250/130341876-256407da-492b-4ff7-9d1e-eacc1c2f76d9.mov

Screen Shot 2021-08-22 at 2 08 43 pm

### CODE REVIEW

**Review by leanne-b — CHANGES_REQUESTED** [review]
Add title for colour scheme selection menu

**Comment by idomo1** [comment]
> Add title for colour scheme selection menu

Done
image

**Review by mt-empty — APPROVED** [review]
All good

**Review by Akshith-Patil — APPROVED** [review]
Looks great!

**Review by leanne-b — APPROVED** [review]

**Pull request merged**
