### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by idomo1**
## Proposed changes

Handle errors from the backend more gracefully.

Screen Shot 2021-09-18 at 7 29 09 pm
Ignore the typo, already been fixed
Screen Shot 2021-09-18 at 7 44 06 pm
Screen Shot 2021-09-18 at 8 57 32 pm

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mt-empty** [comment]
The last one is might be an annoyance to users especially if you have multiple errors

**Review by Akshith-Patil — APPROVED** [review]
Nice👍

**Comment by idomo1** [comment]
@mt-empty It should only ever be shown once with this implementation. The only time it would be shown in production is if the user is offline or the backend is down I think

**Comment by mt-empty** [comment]
Maybe the error `error analysing image` should have a different CSS/color, because currently the error uses the same font as a real defect(description)  
image
 which might confuse users, what do you think?

**Pull request merged**
